name: Package App
on:
  pull_request:
  workflow_dispatch:

jobs:
  package-windows:
    name: Package App - Windows
    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3.1.0

    - name: Set up Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: "3.10"

    - name: Install Briefcase
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install git+https://github.com/rmartin16/briefcase.git@code-signing-windows

    - name: Install Certificate
      run: |
        echo "${{ secrets.CODESIGNING_CERT_B64 }}" | Out-File cert.b64
        certutil -decode cert.b64 cert.pfx
        Import-Certificate -FilePath .\cert.pfx -Cert Cert:\CurrentUser\My -Password ${{ secrets.SIGN_CERT_PASSWORD }}

    - name: Package App
      run: briefcase package windows app --identity aa3a3ac786cb5b323a58d91d2970846723374631 --no-input

    - name: Upload App Exe
      uses: actions/upload-artifact@v3
      with:
        name: app-exe
        path: 'windows\app\Briefcase Test Toga App'
        if-no-files-found: error

    - name: Upload App MSI
      uses: actions/upload-artifact@v3
      with:
        name: app-msi
        path: ' windows\Briefcase Test Toga App-0.0.1.msi'
        if-no-files-found: error

    - name: Delete Build Directory
      run: 'Remove-Item windows -Recurse -Force -Confirm:$false'

    - name: Package App - VS
      run: briefcase package windows visualstudio --identity aa3a3ac786cb5b323a58d91d2970846723374631 --no-input

    - name: Upload App Exe - VS
      uses: actions/upload-artifact@v3
      with:
        name: app-exe-vs
        path: 'windows\VisualStudio\Briefcase Test Toga App'
        if-no-files-found: error

    - name: Upload App MSI - VS
      uses: actions/upload-artifact@v3
      with:
        name: app-msi-vs
        path: 'windows\Briefcase Test Toga App-0.0.1.msi'
        if-no-files-found: error
